name: dependencies
inputs:
  compiler:
    required: true
  compiler_version:
    required: true
  configuration:
    required: true
# An implicit input is the environment variable `build_dir`.
runs:
  using: composite
  steps:
    - name: export custom recipes
      shell: bash
      run: |
        conan export --version 1.1.10 external/snappy
        conan export --version 9.7.3 external/rocksdb
        conan export --version 4.0.3 external/soci
        conan export --version 2.0.8 external/nudb
    - name: add Ripple Conan remote
      shell: bash
      run: |
        conan remote list
        conan remote remove ripple || true
        # Do not quote the URL. An empty string will be accepted (with
        # a non-fatal warning), but a missing argument will not.
        conan remote add ripple --index 0 ${{ env.CONAN_URL }}
    - name: try to authenticate to Ripple Conan remote
      id: remote
      shell: bash
      run: |
        # `conan user` implicitly uses the environment variables
        # CONAN_LOGIN_USERNAME_<REMOTE> and CONAN_PASSWORD_<REMOTE>.
        # https://docs.conan.io/1/reference/commands/misc/user.html#using-environment-variables
        # https://docs.conan.io/1/reference/env_vars.html#conan-login-username-conan-login-username-remote-name
        # https://docs.conan.io/1/reference/env_vars.html#conan-password-conan-password-remote-name
        ## Don't try this yet...
        # echo outcome=$(conan user --remote ripple --password >&2 \
        #   && echo success || echo failure) | tee ${GITHUB_OUTPUT}
    - name: list missing binaries
      id: binaries
      shell: bash
      # Print the list of dependencies that would need to be built locally.
      # A non-empty list means we have "failed" to cache binaries remotely.
      run: |
        # echo missing=$(conan info . --build missing --settings build_type=${{ inputs.configuration }} --json 2>/dev/null  | grep '^\[') | tee ${GITHUB_OUTPUT}
    - name: install dependencies
      env:
        BUILD_TYPE: ${{ inputs.configuration }}
      shell: bash
      run: |
        set -x
        echo $PWD
        python3 <<EOF
        import shutil
        import subprocess
        import sys
        from multiprocessing import cpu_count
        from pathlib import Path

        conanhome = Path(subprocess.check_output(["conan", "config", "home"], text=True).strip())
        conan_profile_path = conanhome / "profiles" / "default"
        global_conf = conanhome / "global.conf"
        default_profile = Path.cwd() / "conan_profile" / "default"
        profile_cmd = ["conan", "profile", "show", "--profile:all", "default"]
        global_defaults = f"""
        tools.build:verbosity = verbose
        tools.build:jobs = {(n:=cpu_count())}
        core.download:parallel = {n}
        core.upload:parallel = {n}
        """

        if conan_profile_path.is_file():
            print(f"conan default profile {conan_profile_path} already exists!")
        else:
            conan_profile_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy(default_profile, conan_profile_path)
            print(f"Copied {default_profile.resolve()} to {conan_profile_path.resolve()}")

        subprocess.run(profile_cmd)

        if "tools.build:verbosity" not in global_conf.read_text(encoding="utf-8"):
            with global_conf.open("a", encoding="utf-8") as f: f.write(global_defaults)

        conan install . \
          --output-folder "${build_dir}" \
          --settings build_type="${BUILD_TYPE}" \
          --build missing
        # conan install . --output-folder "build" --settings build_type="Release" --build missing
        # conan install . --output-folder "build" --settings build_type="Debug" --build missing