name: Build and push image

on:
  push:
  workflow_dispatch:

jobs:
  build_image:
    name: Build images
    uses: ./.github/workflows/reusable-build-image.yml
    permissions:
      packages: write
    with:
      image_name: ghcr.io/${{ github.repository }}
      publishing_repo: legelux/rippled
