name: Build Docker images
env:
  IMAGE: rippled
on:
  push:
    branches:
      - cpack-squash
jobs:
  build_image:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ARM64
          - X64
          # - ARM64
    runs-on: [self-hosted, ARM64]
    name: ${{ matrix.platform }} Docker image build
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: check environment
        run: |
          echo "Building for ${{ matrix.platform }}" > output.txt

      - name: Save output
        uses: actions/upload-artifact@v3
        with:
          name: rippled-${{ matrix.platform }}
          path: output.txt

      # - name: check environment
      #   run: |
      #     echo "Building for ${{ matrix.platform }} "

      # - name: Build image
      #   run: |
      #     docker --version
