name: Test on Linux and MacOS
on: [push, pull_request]

jobs:

  test-rippled-without-conan:
    strategy:
      matrix:
        platform:
          - name: ubuntu-latest
            openssl:
          - name: macos-latest
            openssl: /usr/local/opt/openssl@1.1
        boost:
          - version: 1.77.0
            stem: boost_1_77_0
        compiler:
          - name: gcc
            cxx: g++
            cxxflags:
            linkflags:
        generator:
          - Ninja
        configuration:
          - Release
    runs-on: ${{ matrix.platform.name }}
    env:
      build_dir: .build
    steps:
      - name: install Boost from cache
        id: cache-boost-build
        uses: actions/cache@v2
        with:
          path: ~/${{ matrix.boost.stem }}
          key: build-boost-${{ matrix.boost.version }}-${{ runner.os }}-${{ matrix.compiler.name }}
      - name: download Boost from cache
        if: steps.cache-boost-build.outputs.cache-hit != 'true'
        id: cache-boost-download
        uses: actions/cache@v2
        with:
          path: ~/${{ matrix.boost.stem }}.tar.gz
          key: download-boost-${{ matrix.boost.version }}
      - name: download Boost from internet
        if: steps.cache-boost-download.outputs.cache-hit != 'true'
        run: |
          curl -LO https://boostorg.jfrog.io/artifactory/main/release/${{ matrix.boost.version }}/source/${{ matrix.boost.stem }}.tar.gz
      - name: build Boost
        if: steps.cache-boost-build.outputs.cache-hit != 'true'
        run: |
          cd ~
          tar -zxf ${{ matrix.boost.stem }}.tar.gz
          cd ${{ matrix.boost.stem }}
          ./bootstrap.sh --with-toolset=${{ matrix.compiler.name }}
          ./b2 \
            toolset=${{ matrix.compiler.name }} \
            cxxflags='${{ matrix.compiler.cxxflags }}' \
            linkflags='${{ matrix.compiler.linkflags }}'
      - name: install Ninja on Linux
        if: matrix.generator == 'Ninja' && runner.os == 'Linux'
        run: sudo apt install ninja-build
      - name: install Ninja on OSX
        if: matrix.generator == 'Ninja' && runner.os == 'macOS'
        run: brew install ninja
      - name: install nproc on OSX
        if: runner.os == 'macOS'
        run: brew install coreutils
      - name: checkout
        uses: actions/checkout@v3
      - name: configure
        run: |
          mkdir ${build_dir}
          cd ${build_dir}
          cmake \
            -G ${{ matrix.generator }} \
            -DBOOST_ROOT=~/${{ matrix.boost.stem }} \
            -DOPENSSL_ROOT_DIR=${{ matrix.platform.openssl }} \
            -DCMAKE_C_COMPILER=${{ matrix.compiler.name }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} \
            ..
      - name: build
        run: cmake --build ${build_dir} --target rippled --parallel $(nproc)
      - name: test
        run: ${build_dir}/rippled --unittest --unittest-jobs $(nproc)
