name: Test rippled

on:
  workflow_call:
    inputs:
      pkg_type:
        description: "Whether to run unit tests"
        required: true
        type: boolean

      arch:
        description: Runner to run the job on as a JSON string
        required: true
        type: string
jobs:
  test:
    name: Test ${{ inputs.pkg_type }}-${{ inputs.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { pkg: rpm, distro: "rocky:9" }
          - { pkg: deb, distro: "ubuntu:jammy" }
          - { pkg: deb, distro: "debian:trixie" }
    runs-on: ubuntu-latest
    container: ${{ matrix.distro }}
    steps:
      - name: run unittests
        run: |
            ls -lh
    #   - name: Download rippled artifact
    #     uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
    #     with:
    #       name: rippled-${{ inputs.config_name }}
