on:
  workflow_call:
    inputs:
      pkg_type:
        required: false
        type: string
      arch:
        required: false
        type: string

jobs:
  build:
    name: ${{ matrix.pkg_type }}-${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64"]
        pkg_type: ["deb", "rpm"]
    runs-on: heavy${{ matrix.arch == 'arm64' && '-arm64' || '' }}
    container: ghcr.io/xrplf/ci/${{ matrix.pkg_type == 'rpm' && 'rhel-9' || 'debian-bookworm' }}:gcc-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Build packages
        run: ./pkgs/build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg_type }}-${{ matrix.arch }}
          path: "*${{ matrix.arch }}.${{ matrix.pkg_type }}"
          if-no-files-found: error

  test:
    name: Test ${{ matrix.pkg_type }}-${{ matrix.arch }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64"]
        pkg_type: ["deb", "rpm"]
    runs-on: heavy${{ matrix.arch == 'arm64' && '-arm64' || '' }}
    container: ghcr.io/xrplf/ci/${{ matrix.pkg_type == 'rpm' && 'rhel-9' || 'debian-bookworm' }}:gcc-12
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.pkg_type }}-${{ matrix.arch }}
      - name: Running tests
        run: echo "Running tests..."

  sign:
    name: Sign package ${{ matrix.pkg_type }}-${{ matrix.arch }}
    needs: test
    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64"]
        pkg_type: ["deb", "rpm"]
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:python3.13-bookworm-slim

    steps:
      - name: Install gpg
        run: apt-get update && apt-get install -y gpg

      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.13

      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.pkg_type }}-${{ matrix.arch }}

      - name: Display structure of downloaded files
        run: ls -R
      ## Also possibility
      # - name: Write passphrase file securely
      #   run: |
      #     install -m 600 /dev/null "$RUNNER_TEMP/gpg-pass"
      #     # newline OK; gpg reads to EOF
      #     printf '%s\n' "${{ secrets.GPG_PASSPHRASE }}" > "$RUNNER_TEMP/gpg-pass"

      - name: Sign
        env:
          GPG_KEY_B64: ${{ secrets.GPG_KEY_B64 }}
          GPG_KEY_PASS_B64: ${{ secrets.GPG_KEY_PASS_B64 }}
          PYTHONUNBUFFERED: 1
        run: \
          find . -name "*.${{ matrix.pkg_type }}" -print0 | xargs -0 -I{} ./pkgs/sign_packages.py "{}"

      - uses: actions/upload-artifact@v4
        with:
          name: signed-${{ matrix.pkg_type }}-${{ matrix.arch }}
          path: "*${{ matrix.arch }}.${{ matrix.pkg_type }}"
          if-no-files-found: error
