name: Package rippled

on:
  workflow_call:
    inputs:
      build_type:
        description: 'The build type to use ("Debug", "Release").'
        required: false
        type: string
        default: 'Release'
      cmake_args:
        description: "Additional arguments to pass to CMake."
        required: false
        type: string
      cmake_target:
        description: "The CMake target to build."
        required: false
        type: string

      runs_on:
        description: Runner to run the job on as a JSON string
        required: true
        type: string
      image:
        description: "The image to run in (leave empty to run natively)"
        required: false
        type: string
        default: ''

      config_name:
        description: "The name of the configuration."
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Package ${{ inputs.config_name }}
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    container: ${{ inputs.image != '' && inputs.image || null }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Build packages
        run: |
          export BUILD_TYPE=${{ inputs.build_type }}
          export CMAKE_ARGS=${{ inputs.cmake_args }}
          export CMAKE_TARGETS=${{ inputs.cmake_target }}

          ./pkgs/build.sh

          {
          echo "<table>"
          while IFS='=' read -r k v; do
            printf '<tr><td>%s</td><td align="right"><code>%s</code></td></tr>\n' "$k" "$v"
          done < build_vars
          echo "</table>"
          } >> "$GITHUB_STEP_SUMMARY"

      - uses: actions/upload-artifact@v4
        with:
          name:  ${{ inputs.config_name }}
          path: '**/*.{deb,rpm}'
          if-no-files-found: error
